import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./-components/Navbar/Navbar";
import "@fortawesome/fontawesome-free/css/all.min.css"
import { Toaster } from "sonner";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <Toaster />
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
